// <auto-generated />
namespace Walltage.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class wallidentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wallidentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201507040325523_wall-identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
